export interface SkillMetadata {
  id: string;
  name: string;
  description: string;
  version: string;
}

export interface SkillContractField {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface __APP_PASCAL__Input {
  subject: string;
  context: string;
  requester?: string;
}

export interface __APP_PASCAL__Output {
  summary: string;
  priority: "low" | "medium" | "high";
  actions: string[];
}

export const skillContract = {
  input: [
    {
      name: "subject",
      type: "string",
      required: true,
      description: "Short description of the task or problem the skill will process.",
    },
    {
      name: "context",
      type: "string",
      required: true,
      description: "Longer context block that the skill can inspect for relevant details.",
    },
    {
      name: "requester",
      type: "string",
      required: false,
      description: "Optional requester identifier for traceability.",
    },
  ] satisfies SkillContractField[],
  output: [
    {
      name: "summary",
      type: "string",
      required: true,
      description: "Concise summary generated by the skill.",
    },
    {
      name: "priority",
      type: "\"low\" | \"medium\" | \"high\"",
      required: true,
      description: "Priority classification derived from the input.",
    },
    {
      name: "actions",
      type: "string[]",
      required: true,
      description: "Concrete next actions emitted by the skill.",
    },
  ] satisfies SkillContractField[],
} as const;

export const exampleInput: __APP_PASCAL__Input = {
  subject: "Customer cannot reset password",
  context: "The user is blocked from onboarding because the password reset email does not arrive.",
  requester: "support@__APP_SLUG__.example",
};

export function assertValidOutput(output: __APP_PASCAL__Output): void {
  if (typeof output.summary !== "string" || output.summary.trim().length === 0) {
    throw new Error("Skill output must include a non-empty summary.");
  }

  if (!["low", "medium", "high"].includes(output.priority)) {
    throw new Error(`Skill output priority is invalid: ${String(output.priority)}`);
  }

  if (!Array.isArray(output.actions) || output.actions.length === 0) {
    throw new Error("Skill output must include at least one action.");
  }

  for (const action of output.actions) {
    if (typeof action !== "string" || action.trim().length === 0) {
      throw new Error("Skill output actions must be non-empty strings.");
    }
  }
}
